== Выделение блока

Иногда для правильного выделения блока не хватает просто пустых строк и его необходимо отделить парой разделителей

!=======
| Тип 	| Контекст 	| Модель содержимого | Минимальный разделитель

| comment
| n/a
| n/a
| / / / /

| example
| :example
| compound
| ====

| open
| :open
| compound
| --

| quote
| :quote
| compound
| ____

| sidebar
| :sidebar
| compound
| \****

| table
| :table
| table
a| 
  \|===
  ,===
  :===
  !===
| listing
| :listing
| verbatim
| ----

| literal
| :literal
| verbatim
| ....

| pass
| :pass
| raw
| \\++++

!=======

Здесь не перечислен блок `source` т.к. он является не типом, а специализацией контейнера `listing` с указанием стиля блока;
также как и блоки `verse` или `admonition`, т.е. они перепрофилируют контейнеры блоков `quote` и `example`, соответственно.

Отличной чертой блока комментариев, является то, что он не сохраняется в анализируемом документе и, следовательно, не имеет контекста или модели контента.

Например

[source,asciidoc]
----
====
Текст

из

нескольких

абзацев
====
----

====
Текст

из

нескольких

абзацев
====