== Общие аттрибуты блока

Блоки содержат ноль или более строк метаданных, расположенных построчно непосредственно поверх блока. 
Блоки с разделителями заключаются в соответствующую пару строк-разделителей.

Это могут быть такие строки:

* Ноль или более строк атрибутов блока (которые заполняют атрибуты блока)
* Дополнительная линия привязки блока
* Необязательная строка заголовка блока (многие блоки также поддерживают соответствующий заголовок)
* Дополнительный идентификатор
* Дополнительный набор ролей
* Дополнительный набор опций

Например:

[source,asciidoc]
  .Styles of music
  [#music-styles]
  ****
  Go off on a tangent to describe what a style of music is.
  ****

или без разделителей

[source,asciidoc]
  [quote]
  To be or not to be

Если по блоку нельзя понять контекст, тогда его указывают в начале блока в виде аттрибутов аттрибутами. Первый аттрибут указывает на стиль отображения

[source,asciidoc]
  [source,ruby]
  ----
  puts "Hello, World!"
  ----

Что будет отображено как:

[source,ruby]
----
puts "Hello, World!"
----

Контекст этого блока `listing`, а метка языка `ruby` может указать на стиль оформления.

=== Установка заголовков блока

Для блока можно установить заголовок. Делается это следующим образом

[source,asciidoc]
  .Заголовок блока
  ****
  Содержимое блока
  ****

.Заголовок блока
****
Содержимое блока
****

=== Заголовки с метками

Несколько контекстов блоков поддерживают заголовки с подписью (т.е. ему. предшествует метка заголовка и число, за которым следует точка - например, `Таблица 1. Виды деревьев` )

[source,asciidoc]
  .Заголовок блока
  ====
  Содержимое блока
  ====

.Заголовок блока
====
Содержимое блока
====

Заголовок с подписью используется только в том случае, если установлен соответствующий атрибут.

Подпись можно менять

[source,asciidoc]
  .Заголовок блока
  [caption="Прим. {counter:my-example-number:A}: "]
  ====
  Содержимое блока
  ====

.Заголовок блока
[caption="Прим. {counter:my-example-number:A}: "]
====
Содержимое блока
====

В следующей таблице перечислены блоки, поддерживающие заголовки с подписью, и атрибуты, которые преобразователь использует для их создания и управления.

|====
| Контекст | Аттрибут | Атрибут счетчика

| appendix
| appendix-caption
| appendix-number

| example
| example-caption
| example-number

| image
| figure-caption
| figure-number

| listing, source
| listing-caption
| listing-number

| table
| table-caption
| table-number

|====

=== Идентификатор блока

Идентифицировать блок можно добавлением аттрибута с хешем (#)

[source,asciidoc]
  [#the-id-of-this-block]
  ====
  Content of delimited example block
  ====

В случае, если указан тип блока это делается так:

[source,asciidoc]
  [quote#the-id-of-the-quote,Пушкин,Изречения]
  Чтение - вот лучшее учение

[quote#the-id-of-the-quote,А. С. Пушкин,Избранные изречения]
Чтение - вот лучшее учение